apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-sample-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: java-sample-app
    template:
      metadata:
        labels:
          app: java-sample-app
      spec:
        containers:
          - name: java-sample-app
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            ports:
              - containerPort: 8080